/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.athrun.android.app;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int gallery_01=0x7f020000;
        public static final int gallery_02=0x7f020001;
        public static final int gallery_03=0x7f020002;
        public static final int gallery_04=0x7f020003;
        public static final int gallery_05=0x7f020004;
        public static final int gallery_06=0x7f020005;
        public static final int gallery_07=0x7f020006;
        public static final int gallery_08=0x7f020007;
        public static final int gallery_09=0x7f020008;
        public static final int gallery_10=0x7f020009;
        public static final int gallery_11=0x7f02000a;
        public static final int gallery_12=0x7f02000b;
        public static final int gallery_13=0x7f02000c;
        public static final int gallery_14=0x7f02000d;
        public static final int gallery_15=0x7f02000e;
        public static final int gallery_16=0x7f02000f;
        public static final int gallery_17=0x7f020010;
        public static final int gallery_18=0x7f020011;
        public static final int gallery_19=0x7f020012;
        public static final int gallery_20=0x7f020013;
        public static final int gallery_21=0x7f020014;
        public static final int gallery_22=0x7f020015;
        public static final int gallery_23=0x7f020016;
        public static final int gallery_24=0x7f020017;
        public static final int gridview01=0x7f020018;
        public static final int gridview02=0x7f020019;
        public static final int gridview03=0x7f02001a;
        public static final int gridview04=0x7f02001b;
        public static final int gridview05=0x7f02001c;
        public static final int gridview06=0x7f02001d;
        public static final int gridview07=0x7f02001e;
        public static final int gridview08=0x7f02001f;
        public static final int gridview09=0x7f020020;
        public static final int gridview10=0x7f020021;
        public static final int gridview11=0x7f020022;
        public static final int gridview12=0x7f020023;
        public static final int gridview13=0x7f020024;
        public static final int gridview14=0x7f020025;
        public static final int gridview15=0x7f020026;
        public static final int gridview16=0x7f020027;
        public static final int gridview17=0x7f020028;
        public static final int gridview18=0x7f020029;
        public static final int gridview19=0x7f02002a;
        public static final int gridview20=0x7f02002b;
        public static final int icon=0x7f02002c;
        public static final int imagebg=0x7f02002d;
    }
    public static final class id {
        public static final int ItemImage=0x7f050006;
        public static final int ItemText=0x7f050008;
        public static final int ItemTitle=0x7f050007;
        public static final int LinearLayout01=0x7f050009;
        public static final int RelativeLayout01=0x7f050005;
        public static final int ScrollView=0x7f05001b;
        public static final int btn_another_app=0x7f05000e;
        public static final int btn_gridview_activity=0x7f050011;
        public static final int btn_listview_activity=0x7f050014;
        public static final int btn_sametext_activity=0x7f050015;
        public static final int btn_scrollview_activity=0x7f050012;
        public static final int btn_textview_activity=0x7f05000f;
        public static final int btn_textviewtree_activity=0x7f050010;
        public static final int btn_webview_activity=0x7f050013;
        public static final int gridviewitem_image=0x7f050002;
        public static final int gridviewitem_text=0x7f050003;
        public static final int include_checkbox=0x7f050016;
        public static final int mainroot=0x7f05000b;
        public static final int my_autocompletetextview=0x7f050022;
        public static final int my_checkbox=0x7f050000;
        public static final int my_checkedtextview=0x7f050023;
        public static final int my_edittext=0x7f050021;
        public static final int my_gallery=0x7f05000d;
        public static final int my_gridview=0x7f050004;
        public static final int my_imageview=0x7f05000c;
        public static final int my_last_edittext=0x7f050027;
        public static final int my_linearlayout=0x7f05001f;
        public static final int my_listview=0x7f05000a;
        public static final int my_multiautocompletetextview=0x7f050024;
        public static final int my_progressbar=0x7f050031;
        public static final int my_textview=0x7f050020;
        public static final int my_togglebutton=0x7f050026;
        public static final int mywebview=0x7f050032;
        public static final int next_webview=0x7f050030;
        public static final int same_one=0x7f050018;
        public static final int same_three=0x7f05001a;
        public static final int same_two=0x7f050019;
        public static final int sameroot=0x7f050017;
        public static final int scroll_button=0x7f05001c;
        public static final int scroll_button2=0x7f05001e;
        public static final int scroll_textview=0x7f05001d;
        public static final int textview=0x7f050001;
        public static final int textview_checkbox=0x7f050025;
        public static final int textviewtree_one_one=0x7f050029;
        public static final int textviewtree_one_three=0x7f05002b;
        public static final int textviewtree_one_two=0x7f05002a;
        public static final int textviewtree_root=0x7f050028;
        public static final int textviewtree_two_one=0x7f05002c;
        public static final int textviewtree_two_three=0x7f05002e;
        public static final int textviewtree_two_two=0x7f05002d;
        public static final int webview_extend=0x7f05002f;
    }
    public static final class layout {
        public static final int checkbox_layout=0x7f030000;
        public static final int gridview_item_layout=0x7f030001;
        public static final int gridview_layout=0x7f030002;
        public static final int listview_item_layout=0x7f030003;
        public static final int listview_layout=0x7f030004;
        public static final int main=0x7f030005;
        public static final int sametext_layout=0x7f030006;
        public static final int scrollview_layout=0x7f030007;
        public static final int textview_layout=0x7f030008;
        public static final int textview_tree_layout=0x7f030009;
        public static final int webview_extend_layout=0x7f03000a;
        public static final int webview_layout=0x7f03000b;
    }
    public static final class string {
        public static final int another_app=0x7f040012;
        public static final int app_name=0x7f040000;
        public static final int edittext=0x7f040003;
        public static final int gridview=0x7f040010;
        public static final int listview=0x7f040006;
        public static final int mapview=0x7f040011;
        public static final int one_one=0x7f040009;
        public static final int one_two=0x7f04000a;
        public static final int sametext=0x7f040013;
        public static final int scroll_text=0x7f040001;
        public static final int scrollview=0x7f040004;
        public static final int scrollview_button_bottom=0x7f040008;
        public static final int scrollview_button_top=0x7f040007;
        public static final int textview=0x7f040002;
        public static final int textviewtree=0x7f04000b;
        public static final int three_one=0x7f04000e;
        public static final int three_two=0x7f04000f;
        public static final int two_one=0x7f04000c;
        public static final int two_two=0x7f04000d;
        public static final int webview=0x7f040005;
    }
}
